version: "3"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ikki
      POSTGRES_PASSWORD: pass%word
      POSTGRES_DB: pg_dms
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    networks:
      - dms-dev
    volumes:
      - dms-pg-data:/var/lib/postgresql/data
      - ./postgresql/init.d:/docker-entrypoint-initdb.d
    container_name: dms-postgres

  mysql:
    image: mysql:8.0
    volumes:
      - dms-ms-data:/var/lib/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - ./mysql/custom.conf:/etc/mysql/conf.d/custom.conf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_dms
    networks:
      - dms-dev
    container_name: dms-mysql

  zookeeper:
    image: debezium/zookeeper:1.8
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - dms-zookeeper-data:/zookeeper/data
      - dms-zookeeper-txns:/zookeeper/txns
    networks:
      - dms-dev

  kafka:
    image: debezium/kafka:1.8
    ports:
      - 9092:9092
      - 29092:29092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=FROM_DOCKER_NETWORK://0.0.0.0:9092,FROM_HOST://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=FROM_DOCKER_NETWORK://kafka:9092,FROM_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,FROM_DOCKER_NETWORK:PLAINTEXT,FROM_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=FROM_DOCKER_NETWORK
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - dms-kafka-data:/kafka/data
    networks:
      - dms-dev
    container_name: dms-local-kafka

  connect:
    image: debezium/connect:1.8
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - dms-dev

volumes:
  dms-pg-data:
  dms-ms-data:
  dms-kafka-data:
  dms-zookeeper-data:
  dms-zookeeper-txns:

networks:
  dms-dev:
    external: true
