version: "3"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ikki
      POSTGRES_PASSWORD: pass%word
      POSTGRES_DB: pg_dms
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    networks:
      - dms-dev
    volumes:
      - dms-pg-data:/var/lib/postgresql/data
      - ./postgresql/init.d:/docker-entrypoint-initdb.d
    container_name: dms-postgres

  mysql:
    image: mysql:8.0
    volumes:
      - dms-ms-data:/var/lib/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - ./mysql/custom.conf:/etc/mysql/conf.d/custom.conf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_dms
    networks:
      - dms-dev
    container_name: dms-mysql

  zookeeper:
    image: debezium/zookeeper:1.8
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - dms-dev

  kafka:
    image: debezium/kafka:1.8
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - dms-dev

  connect:
    image: debezium/connect:1.8
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - dms-dev

volumes:
  dms-pg-data:
  dms-ms-data:

networks:
  dms-dev:
    external: true
