USE ms_dms;
DROP TABLE IF EXISTS user;

CREATE TABLE user(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(25) NOT NULL,
  delete_flag tinyint(1) NOT NULL
) DEFAULT CHARACTER SET=utf8mb4;
